name: Test - Third Workflow

on:
  workflow_run:
    workflows: ["Test - Workflow Run"]
    branches: ["dev"]
    types:
      - completed

env:
############# DEPLOY RC ##############
  INSTANCE_TO_DEPLOY: "-l preproduction"
  NODEJS_GIT_BRANCH: ""
  PLAYBOOKS_TAGS: ""

jobs:
  test_workflow_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo ${{ github.event.workflow_run.head_branch }}
