name: Test - Workflow Run

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Test - Base Workflow"]
    branches: ["master"]
    types:
      - completed

jobs:
  test_workflow_run:
    if: github.event.workflow_run.head_branch == 'master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo ${{ github.event.workflow_run.head_branch }}
