name: Test - Third Workflow

on:
  workflow_dispatch:
    inputs:
      nodejs_git_branch:
        description: NodeJS git branch
        default: ''
        required: true
      playbook_tags:
        description: limit playbook execution to the following tags
        default: ''
        required: false
  workflow_run:
    workflows: ["Test - Workflow Run"]
    branches: ['rc']
    types:
      - completed

env:
############# DEPLOY RC ##############
  INSTANCE_TO_DEPLOY: "-l preproduction"
  NODEJS_GIT_BRANCH: ""
  PLAYBOOKS_TAGS: ""

jobs:
  test_workflow_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo ${{ github.event.workflow_run.head_branch }}
